Qovery/engine

- lib/aws/bootstrap/helm-qovery-engine.tf
- lib/common/bootstrap/charts/qovery-engine/values.yaml
- lib/digitalocean/bootstrap/helm-qovery-engine.tf
- src/models.rs
- test_utilities/src/utilities.rs
In order to get the same variable name everywhere
> Harmonize env variable from NATS_SERVER to QOVERY_NATS_URL

- lib/aws/bootstrap/chart_values/prometheus_operator.yaml
- lib/digitalocean/bootstrap/chart_values/prometheus_operator.yaml
Before, we were using kube-state-metrics from Prometheus operator chart. But because we can't control resource usage, it may be preferable to use the dedicated chart for it.
I disable it because Terraform was failing on chart upgrade (because of pod CrashloopBackoff)
> feat: temporary remove kube-state-metrics

- src/cloud_provider/digitalocean/router.rs
- src/cloud_provider/utilities.rs
+ For custom domain we ask users to point with a CNAME
to xxx.qovery.io. If the user is using a CDN, it is not
possible to check if the configuration is correct as
there will be no CNAME records avaible and A record
is going to match IP of the CDN
> Do not fail deployment if CNAME is not valid

- Cargo.lock
- Cargo.toml
- src/cmd/utilities.rs
- reading on stdout/stderr may be blocking if the app does
not output anything, thus we never reach the code that abort/timeout
the process
- Fix: Properly timeout reading stdout/stderr
- Try to interleave stdout and stderr to have output in the correct
order. For a better alternative timestamp should be added and remerged
after it
> Fix command with timeout

- lib/aws/chart_values/nginx-ingress/nginx-ingress.j2.yaml
- lib/digitalocean/bootstrap/chart_values/nginx-ingress.j2.yaml
- lib/digitalocean/chart_values/nginx-ingress/nginx-ingress.j2.yaml
- src/cloud_provider/aws/router.rs
- src/cloud_provider/digitalocean/router.rs
* For production usage, autoscaler is enabled with more resources
* For dev usage, autoscaler is disabled, only 1 nginx is running with a small amount of resources
> feat: reduced resource usage for custom domains

- Cargo.lock
- Cargo.toml
- src/fs.rs
This CL introduces:
- rename generated archive with the proper extension 'tgz' instead of
'tar.gz'
- a way to exclude files / folders for generated archive
- excludes terraform's folder and hcl
DEV-897
> feat: move out terraform folder form engine archive

- src/build_platform/local_docker.rs
- src/build_platform/mod.rs
- src/models.rs
- test_utilities/src/aws.rs
- Change to support mono-repo, aka being able to build image from other directory than the root of the repository.
- Fix: Don't try to use buildkit if the specified Dockerfile is not present in the repository
> Add support for mono-repo with multiple build context

- lib/aws/charts/q-application/templates/deployment.j2.yaml
- lib/aws/charts/q-application/templates/statefulset.j2.yaml
- lib/digitalocean/charts/q-application/templates/deployment.j2.yaml
- lib/digitalocean/charts/q-application/templates/statefulset.j2.yaml
- tests/aws/aws_environment.rs
+ In order to implement restart, we want to force rollout even
if nothing changes in the deployment
+ CREATE action should be renamed DEPLOY to be more insightfull
> Force deployment restart on helm upgrade

- src/build_platform/local_docker.rs
+ Returning sterr message as error make deployments fails
+ Stderr message can only be warning (i.e: npm messages)
+ Relies on of docker build exit code to tell if build is in error or not
> Change logging lvl for stderr message during docker build

- lib/aws/charts/q-application/templates/deployment.j2.yaml
- lib/digitalocean/charts/q-application/templates/deployment.j2.yaml
When there is one app with only one instance, the rollout delete the app before deploying the new one, causing small downtimes. We now check the number of desired instances and adapt the config if set to 1.
> fix: ensure 1 app is always available when only 1 instance is deployed

- lib/aws/chart_values/nginx-ingress/nginx-ingress.j2.yaml
By enabling this option the controller is going to
use a service to know the ingress endpoint/address to use.
In our case, it is going to pick the LB hostname thus
it is going to avoid the need to add on every ingress
target annotation for external DNS with the LB hostname.
This reduce the toil to update LB endpoint when it changes,
as it is done automatically now
> Enable publish service for nginx-ingress

- tests/scaleway/scw_kubernetes.rs
This CL adds `qovery-test-` prefix to test clusters.
> tests: prepend qovery test to test clusters

- Cargo.lock
- Cargo.toml
- lib/common/bootstrap/charts/qovery-engine/templates/statefulset.yaml
- test_utilities/Cargo.lock
In order to avoid wrong behavior on the engine, it's preferable to disable automount token to deny then engine to have k8s api access on the cluster it's running
> feat: disable automount token on engine

- lib/scaleway/bootstrap/chart_values/nginx-ingress.yaml
- test_utilities/src/utilities.rs
Fixing not working scaleway router declaration preventing to reach service from external DNS.
> fix: scaleway router DNS not accessible

- src/cloud_provider/aws/kubernetes/helm_charts.rs
This CL introduced a bug preventing AWS cluster to reach the outside
world.
This reverts commit c8e1f2aad1bc8b36d8896be2967555c2238a7ea6.
> Revert "feat: eks enable vpc peering by default"

- lib/common/bootstrap/charts/cluster-autoscaler/values.yaml
This CL increase cluster-autoscaler memory from 300Mi to 512Mi. It seems
300Mi is not enough in some cases preventing it to properly boot.
> fix: give more memory to cluster-autoscaler

- src/fs.rs
This CL fixes a bug preventing the engine to properly delete the
qovery_workspace for a finished task due to a trailing "./" leading to
file system not whiling to delete directory.
> fix: removing trailing './' from workspace_dir to be deleted

- lib/aws/charts/q-ingress-tls/templates/ingress-qovery.j2.yaml
- lib/digitalocean/charts/q-ingress-tls/templates/ingress-qovery.j2.yaml
- lib/scaleway/charts/q-ingress-tls/templates/ingress-qovery.j2.yaml
We're disabling it by default as it's not secure. Was useful for some
clients but not the things to do.
It's disabled now but will come back as options to set by the customer
directly from the UI.
> refactor: disable CORS by default

- lib/common/bootstrap/charts/qovery-engine/templates/autoscaler.yaml
- lib/common/bootstrap/charts/qovery-engine/templates/pdb.yaml
- lib/common/bootstrap/charts/qovery-engine/templates/secret.yaml
- lib/common/bootstrap/charts/qovery-engine/templates/service.yaml
- lib/common/bootstrap/charts/qovery-engine/templates/serviceaccount.yaml
- lib/common/bootstrap/charts/qovery-engine/templates/servicemonitor.yaml
- lib/common/bootstrap/charts/qovery-engine/templates/statefulset-deploy.yaml
- lib/common/bootstrap/charts/qovery-engine/values.yaml
Engines now supports 2 modes:
1. statefulset when builders are active
2. deployments when no builders to grow faster the number of instances
and prepare for autoscaling
> feat: engines as deployments when no builder

- lib/digitalocean/bootstrap/tf-default-vars.j2.tf
- tests/digitalocean/do_kubernetes.rs
Introduces new naming method for DO clusters. New naming will be
`qovery-` followed by the cluster ID.
JIRA: DEV-1009
> fix: DO cluster naming

- src/object_storage/spaces.rs
DO spaces doesn't support bucket creation if location is specified using rusoto
> fix: DO space bucket creation

- lib/aws/services/mongodb/main.j2.tf
- lib/aws/services/mongodb/variables.j2.tf
- lib/aws/services/mysql/main.j2.tf
- lib/aws/services/mysql/variables.j2.tf
- lib/aws/services/postgresql/main.j2.tf
- lib/aws/services/postgresql/variables.j2.tf
- lib/aws/services/redis/main.j2.tf
- lib/aws/services/redis/variables.j2.tf
- src/cloud_provider/aws/databases/mongodb.rs
- src/cloud_provider/aws/databases/mysql.rs
- src/cloud_provider/aws/databases/postgresql.rs
- src/cloud_provider/aws/databases/redis.rs
- src/cloud_provider/aws/databases/utilities.rs
Note: this makes tests way longer, but this is the only way to test it
properly. If it was the case before, this bug would never happen
> fix: aws managed services couldn't be deleted

- src/cloud_provider/aws/kubernetes/mod.rs
- src/cloud_provider/digitalocean/kubernetes/mod.rs
- src/cloud_provider/scaleway/kubernetes/mod.rs
In order to manage several deployment steps on the infra deletion part, specifically when kubeconfig cannot be retrieved, I've added a way to skip this part and move directly to terraform destroy
> fix: skip kubernetes content delete if kubeconfig can't be retrieved

- tests/scaleway/scw_kubernetes.rs
- remove useless SCW infra tests attributes
- ignores infra cluster creation test in Paris 1
- activate infra cluster creation test in Paris 2
> tests: SCW update infra tests

- src/cloud_provider/helm.rs
- src/cmd/helm.rs
- src/models.rs
- move helm lock clean outside the Clojure receiving logs, because there is no guarantee that the Helm process is terminated at this moment. Doing it at this location can result of removing the lock while helm is still running.
- Don't try to parse stderr if the flag is not set. I am not  even sure that checking stderr is necessary, because I think it was just the helm process exit status that was not properly propagated.  exit_status == 1 returnin Ok(()), making believe helm succeeded.
> Do not always fail helm on stderr message

- src/cloud_provider/aws/router.rs
- src/cloud_provider/digitalocean/router.rs
- src/cloud_provider/scaleway/router.rs
- When deployment of an env fail, the upper layer is calling
on_create_error() on all services (db + app + routers)
thus if an app fails to be deployed we delete his router/ingress
leaving his environment broken
> Fix un-wanted router deletion

- Cargo.lock
- Cargo.toml
- src/build_platform/local_docker.rs
- src/cloud_provider/digitalocean/kubernetes/cidr.rs
- src/cmd/helm.rs
- src/cmd/kubectl.rs
- src/cmd/structs.rs
- src/cmd/terraform.rs
- src/cmd/utilities.rs
- src/container_registry/docker.rs
- src/container_registry/docker_hub.rs
- src/container_registry/docr.rs
- src/container_registry/ecr.rs
- src/models.rs
- src/object_storage/s3.rs
- test_utilities/Cargo.lock
- test_utilities/src/utilities.rs
- Remove SimpleError and introduce a proper error
- Encapsulate commands
- Re-use exec_with_timeout for exec_with_output
- Simplify lambda to capture stdout/stderr from Result<String, Error> to String
> Exec refacto

- src/build_platform/local_docker.rs
- src/git.rs
- Properly set login/password to repository url
They were not correctly escaped before
- Use git reset --hard to checkout because we were trying
to change (badly) the HEAD which is what reset does
- Simplify + Handle all errors instead of swallowing them
- Add some tests
> Refacto git operations

- .github/workflows/tests.yml
Deactivating cargo audit for the time being as couple libraries raises some errors (DO lib). We will re-activate this check once moved out of those libs.
Ticket: ENG-1089
> tests: remove audit rs checks for the time being

- src/build_platform/docker.rs
Hi, here is a fix for build args injection while building a Docker image. It didn't work because of the bad assumptions of the format of `env_var_args`.
> fix build args injection while building docker image

- src/cloud_provider/aws/kubernetes/mod.rs
- src/cloud_provider/digitalocean/kubernetes/mod.rs
- src/cloud_provider/scaleway/kubernetes/mod.rs
This CL lowers down the number of crashlooping pods restarts to be
consired as to be deleted from 5 to 3.
> feat: lower restarts to delete crashlooping pods

- lib/aws/charts/q-application/templates/service.j2.yaml
- lib/digitalocean/charts/q-application/templates/service.j2.yaml
- lib/scaleway/charts/q-application/templates/service.j2.yaml
As of today if port is set as private on an app / db, then no service
will be created for it in k8s. This should not be the case and a service
should be created even if app or db is flagged as private allowing other
internal apps to connect to it.
> fix: service to be created even if private port

- lib/common/bootstrap/charts/qovery-shell-agent/templates/clusterrole.yaml
+ Some kube lib (i.e: kube-rs) is doing a get before doing
a create
> Fix rbac for shell-agent

- lib/aws/charts/q-application/templates/service.j2.yaml
- lib/digitalocean/charts/q-application/templates/service.j2.yaml
- lib/scaleway/charts/q-application/templates/service.j2.yaml
This CL fixes a bug: in case there is no port defined in service, it produces an invalid YAML. This fix prevent service to be created in case there is no ports defined.
> fix: handle services without ports defined

- src/cloud_provider/helm.rs
This CL increases default helm chart timeout from 180 seconds to 300 seconds.
> conf: increase default helm timeout

- src/cloud_provider/kubernetes.rs
- Multiple stateful services trigger the on_create_check()
before service are deployed every time
- stateless services were check mulitples times also
> Fix deployment flow

- src/container_registry/scaleway_container_registry.rs
As of today, we use only one container registry per customer account.
Hence we take the first registry namespace matching our filters but we
do not check if this one is ready.
This CL aims to prevent us from picking a registry if its status is not
Ready.
> improvement: check SCW CR is ready before to use it

- lib/aws/services/common/common-variables.j2.tf
- lib/aws/services/redis/main.j2.tf
Postgres, mysql use the var.publicly_accesible terraform variable, but this one is never set outside of the default true
> Fix: AWS managed database are never private

- src/cloud_provider/kubernetes.rs
- src/cloud_provider/service.rs
we were always executing the create check action, even in case of pause/delete
> Fix: execute correct check action during deployment

- src/cloud_provider/aws/kubernetes/mod.rs
- src/cloud_provider/digitalocean/kubernetes/mod.rs
- src/cloud_provider/kubernetes.rs
- src/cloud_provider/scaleway/kubernetes/mod.rs
- src/events/io.rs
- src/events/mod.rs
- src/logger.rs
This CL aims to ease and simplify EventMessage usage making safe /
unsafe message more transparent to deal with.
> refactor: ease event message safe / unsafe logic

- src/logger.rs
New STD IO logging system sends short version of the execution ID, but
it's better to have its full version for convenience.
> feat: logger to send full execution ID

- lib/scaleway/services/mysql/main.j2.tf
- lib/scaleway/services/postgresql/main.j2.tf
- test_utilities/src/common.rs
- tests/scaleway/scw_databases.rs
As of today, SCW doesn't support `is_publicly_accessible` tag on their
managed DB terraform provider nor any other tags related to DB access.
This CL fix this bug along with fixing SCW managed DB tests where those
requires strong passwords instead of Uuids in tests.
> fix: remove unknown param for SCW managed DB

- lib/digitalocean/bootstrap/tf-providers.j2.tf
- lib/scaleway/bootstrap/tf-providers.j2.tf
For aws use v3.66.0, while not for do and scaleway, which require 400meg more of data in the container
> Terraform: Use same version of aws provider everywhere

- lib/common/bootstrap/charts/qovery-engine/templates/statefulset-deploy.yaml
- lib/common/bootstrap/charts/qovery-engine/values.yaml
In order to avoid using network storage, bringing random performances on container build, we're going to try local storage instead and see how it behaves
> feat: add ephemeral storage to engine

- lib/aws/charts/q-application/templates/deployment.j2.yaml
- lib/digitalocean/charts/q-application/templates/deployment.j2.yaml
- lib/scaleway/charts/q-application/templates/deployment.j2.yaml
- src/cloud_provider/service.rs
- src/error.rs
- src/errors/mod.rs
- src/events/io.rs
- src/events/mod.rs
- src/logger.rs
- src/models/application.rs
This CL adds:
- application commit ID to some application actions logs.
- application commit ID annotation / label to application deployment
yaml so it can be retrieved later on from other services
Ticket: ENG-1170
> feat: add application commit ID to logs

- lib/aws/bootstrap/eks-master-cluster.j2.tf
- lib/digitalocean/bootstrap/ks-locals.j2.tf
- lib/scaleway/bootstrap/ks-locals.j2.tf
- src/cloud_provider/aws/kubernetes/mod.rs
- src/cloud_provider/scaleway/kubernetes/mod.rs
- Managed Databases use the clusterId in order find back the VPC
> Fix: revert clusterId to be a short id

- tests/aws/aws_kubernetes_ec2.rs
AWS EC2 not being ready yet, tests should be deactivated for the time being.
> tests: ignore AWS EC2 infra tests
