Qovery/engine

- lib/aws/services/mysql/main.j2.tf
- lib/aws/services/mysql/variables.j2.tf
- lib/aws/services/postgresql/main.j2.tf
- lib/aws/services/postgresql/variables.j2.tf
- src/cloud_provider/aws/databases/mysql.rs
- src/cloud_provider/aws/databases/postgresql.rs
- src/models.rs
> fix: rds test retention backups

- src/cloud_provider/aws/application.rs
- src/cloud_provider/aws/common.rs
- src/cloud_provider/aws/databases/mod.rs
- src/cloud_provider/aws/databases/mongodb.rs
- src/cloud_provider/aws/databases/mysql.rs
- src/cloud_provider/aws/databases/postgresql.rs
- src/cloud_provider/aws/databases/redis.rs
- src/cloud_provider/aws/external_service.rs
- src/cloud_provider/aws/kubernetes/mod.rs
- src/cloud_provider/aws/router.rs
- src/cloud_provider/digitalocean/application.rs
- src/cloud_provider/digitalocean/databases/postgresql.rs
- src/cloud_provider/digitalocean/router.rs
- src/cloud_provider/kubernetes.rs
- src/cloud_provider/service.rs
- src/cmd/kubectl.rs
- src/cmd/structs.rs
- src/container_registry/docr.rs
- src/object_storage/do_space.rs
chore: add kubectl command to list Kubernetes pod events
> improve error output provided to the user

- src/build_platform/local_docker.rs
- src/cloud_provider/aws/application.rs
- src/cloud_provider/aws/common.rs
- src/cloud_provider/aws/databases/mod.rs
- src/cloud_provider/kubernetes.rs
- src/cmd/kubectl.rs
- src/cmd/structs.rs
fix: support other OS than Linux
> fix: show k8s events on deployment error

- lib/aws/bootstrap/helm-cert-manager.j2.tf
- lib/digitalocean/bootstrap/helm-cert-manager.j2.tf
https://cert-manager.io/docs/configuration/acme/dns01/#setting-nameservers-for-dns01-self-check
> feat: force cert-manager to use specific DNS to speed up resolution

- src/template.rs
> Revert "Update template.rs"

- src/object_storage/mod.rs
- src/object_storage/s3.rs
- src/object_storage/spaces.rs
> add ObjectStorage.put(..) function to upload object on S3 and Spaces

- src/build_platform/local_docker.rs
- src/build_platform/mod.rs
- src/models.rs
- test_utilities/src/aws.rs
- test_utilities/src/utilities.rs
- tests/aws/aws_databases.rs
- tests/aws/aws_environment.rs
Provides buildpacks support to Qovery. This PR turns Dockerfile optional. Which is convenient for 90% of Qovery users.
> Support buildpacks

- src/cloud_provider/aws/application.rs
- src/cloud_provider/aws/databases/postgresql.rs
- src/cloud_provider/aws/router.rs
- src/cloud_provider/digitalocean/application.rs
- src/cloud_provider/digitalocean/common.rs
- src/cloud_provider/digitalocean/kubernetes/cidr.rs
- src/cloud_provider/digitalocean/router.rs
- src/cloud_provider/kubernetes.rs
- src/cloud_provider/service.rs
- src/cloud_provider/utilities.rs
- src/object_storage/spaces.rs
- test_utilities/src/digitalocean.rs
- test_utilities/src/utilities.rs
- tests/dns.rs
> Remove warnings

- README.md
I think I've noticed small typos. Feel free to close if I'm wrong :)
> README.md: typos

- src/cmd/utilities.rs
+ Do not use pipe for stdout/stderr when we don't read back output
+ Reap children when we check if a binary exist
> Fix: Process handling

- src/cloud_provider/aws/databases/mongodb.rs
- src/cloud_provider/aws/databases/mysql.rs
- src/cloud_provider/aws/databases/postgresql.rs
- src/cloud_provider/utilities.rs
Upgrade first to fix an issue with RDS PostgreSQL
> feat: upgrading databases versions

- src/cloud_provider/service.rs
- src/cmd/structs.rs
- Try to fetch as much as possible info instead of aborting
at first error
> Do not abort at first error when retrieving debug info

- src/build_platform/local_docker.rs
In order to maximize the space gain after a docker prune, I've added volumes and containers
> fix: add new prune commands

- Cargo.lock
- src/container_registry/ecr.rs
* Enhance ECR reliability because of too many random errors (200 return code from AWS API while it's not ready yet)
* Reduced to 1 day ECR policy for test purpose
> feat: enhance ECR reliability and policy

- src/models.rs
+ If user change the root path of is application without deploying a new commit, we deploy the wrong image as it may be in cache
> Add root_path in image tag

- .github/workflows/tests.yml
- Cargo.lock
- Cargo.toml
- src/models.rs
This CL introduces:
- a security-check workflow aiming to check packages security issues
- updating project packages fixing security issues
> sec: update dependencies for sec

- lib/digitalocean/chart_values/redis/values.j2.yaml
- src/cloud_provider/aws/application.rs
- src/cloud_provider/digitalocean/application.rs
- src/cloud_provider/service.rs
- src/cmd/kubectl.rs
+ All databases does not have the same naming depending on the chart
+ Use a selector in order to be sure that we target the correct
component
> Fix down scaling of database

- lib/common/services/mongodb/templates/deployment-standalone.yaml
- lib/common/services/mysql/templates/master-statefulset.yaml
- lib/common/services/redis/templates/redis-master-statefulset.yaml
- lib/helm-freeze.yaml
+ Replicas is not specified in charts so after the pause
Helm install does not scale back statefulset to 1
+ Force replicas in chart to 1 to ensure that helm upgrade scale it back
+ Fix for MySQL were labels are not applied
https://qovery.atlassian.net/browse/DEV-927
> Fix: Pause action

- lib/scaleway/bootstrap/ks-workers-nodes.j2.tf
- src/cloud_provider/scaleway/kubernetes/mod.rs
This CL use variables instead of hardcoded values in the nodes / pool
kubernetes template.
> feat: scaleway add pool config params

- src/cloud_provider/digitalocean/kubernetes/mod.rs
- tests/digitalocean/do_kubernetes.rs
This CL allows to delete DigitalOcean clusters
> feat: DO implement cluster deletion

- lib/scaleway/charts_values/mongodb/values.j2.yaml
- lib/scaleway/charts_values/mysql/values.j2.yaml
- lib/scaleway/charts_values/postgresql/values.j2.yaml
- lib/scaleway/charts_values/redis/values.j2.yaml
- src/cloud_provider/scaleway/databases/mod.rs
- src/cloud_provider/scaleway/databases/mongodb.rs
- src/cloud_provider/scaleway/databases/mysql.rs
- src/cloud_provider/scaleway/databases/postgresql.rs
- src/cloud_provider/scaleway/databases/redis.rs
- src/cloud_provider/scaleway/mod.rs
- src/models.rs
- tests/scaleway/mod.rs
- tests/scaleway/scw_databases.rs
> feat: scaleway support container DBs

- src/cloud_provider/scaleway/kubernetes/mod.rs
- src/object_storage/scaleway_object_storage.rs
- test_utilities/src/scaleway.rs
- tests/scaleway/scw_object_storage.rs
> feat: scaleway object storage do not activate versioning per default

- lib/common/bootstrap/charts/qovery-engine/templates/statefulset.yaml
- lib/common/bootstrap/charts/qovery-engine/values.yaml
In order to avoid having the build container inside the engine, here is a feature flag
> feat: add engine build feature flag

- src/build_platform/local_docker.rs
- src/build_platform/mod.rs
- src/models.rs
- test_utilities/src/common.rs
Allow to specify the language/pack that buildpacks should use instead of relying on the auto detect feature
> Add buildpack language support

- lib/aws/charts/q-application/templates/deployment.j2.yaml
- lib/aws/charts/q-application/templates/networkpolicies.j2.yaml
- lib/aws/charts/q-application/templates/pdb.j2.yaml
- lib/aws/charts/q-application/templates/secret.j2.yaml
- lib/aws/charts/q-application/templates/service.j2.yaml
- lib/aws/charts/q-application/templates/statefulset.j2.yaml
- lib/digitalocean/charts/q-application/templates/deployment.j2.yaml
- lib/digitalocean/charts/q-application/templates/pdb.j2.yaml
- lib/digitalocean/charts/q-application/templates/secret.j2.yaml
- lib/digitalocean/charts/q-application/templates/service.j2.yaml
- lib/digitalocean/charts/q-application/templates/statefulset.j2.yaml
- lib/scaleway/charts/q-application/templates/deployment.j2.yaml
- lib/scaleway/charts/q-application/templates/networkpolicies.j2.yaml
- lib/scaleway/charts/q-application/templates/pdb.j2.yaml
- lib/scaleway/charts/q-application/templates/secret.j2.yaml
- lib/scaleway/charts/q-application/templates/service.j2.yaml
- lib/scaleway/charts/q-application/templates/statefulset.j2.yaml
This is to fix issue where helm is unable to patch objet because he cannot determine the key for port object
> Add name in ports service & remove ownerId

- test_utilities/src/aws.rs
In order to remove dmu cluster I switch to the new test cluster ID zbe9e22b0
> Update aws test cluster

- tests/digitalocean/do_spaces.rs
Do doesn't support tags for spaces but allow spaces recreation.
Just adding a test for it.
> tests: DO adding spaces recreate test

- src/cloud_provider/scaleway/kubernetes/mod.rs
- src/object_storage/scaleway_object_storage.rs
- test_utilities/src/scaleway.rs
- tests/scaleway/scw_object_storage.rs
* Adding tagging TTL + creation date
* Adding bucket recreate test
> tests: SCW adding object storage recreate test

- Cargo.lock
- Cargo.toml
- src/errors/io.rs
- src/errors/mod.rs
- src/lib.rs
- src/models.rs
- test_utilities/Cargo.lock
> feat: introduce new error handling models

- src/errors/mod.rs
- src/events/mod.rs
- src/logger.rs
- test_utilities/src/utilities.rs
> feat: implement new std io logger

- src/cloud_provider/aws/kubernetes/helm_charts.rs
- src/cloud_provider/helm.rs
- src/cmd/kubectl.rs
> feat: delete crash-looping pod before deploy

- Cargo.lock
- Cargo.toml
- src/build_platform/local_docker.rs
- src/build_platform/mod.rs
- src/git.rs
- src/models.rs
- test_utilities/Cargo.lock
> Add support for ssh key during git submodule

- src/build_platform/local_docker.rs
- src/git.rs
> Git Ssh: Make it bullet proof and use provided user

- Cargo.lock
- lib/aws/charts/q-ingress-tls/templates/ingress-qovery.j2.yaml
- lib/digitalocean/charts/q-ingress-tls/templates/ingress-qovery.j2.yaml
- lib/scaleway/charts/q-ingress-tls/templates/ingress-qovery.j2.yaml
- src/cloud_provider/aws/router.rs
- src/cloud_provider/digitalocean/router.rs
- src/cloud_provider/scaleway/router.rs
- src/models.rs
- test_utilities/Cargo.lock
- test_utilities/Cargo.toml
- test_utilities/src/common.rs
- test_utilities/src/utilities.rs
- tests/aws/aws_databases.rs
- tests/aws/aws_environment.rs
- tests/aws/aws_kubernetes.rs
- tests/aws/aws_whole_enchilada.rs
- tests/digitalocean/do_databases.rs
- tests/digitalocean/do_environment.rs
- tests/digitalocean/do_kubernetes.rs
- tests/digitalocean/do_spaces.rs
- tests/digitalocean/do_utility_kubernetes_doks_test_cluster.rs
- tests/digitalocean/do_whole_enchilada.rs
- tests/scaleway/scw_container_registry.rs
- tests/scaleway/scw_databases.rs
- tests/scaleway/scw_environment.rs
- tests/scaleway/scw_kubernetes.rs
- tests/scaleway/scw_object_storage.rs
- tests/scaleway/scw_utility_kubernetes_kapsule_test_cluster.rs
- tests/scaleway/scw_whole_enchilada.rs
> feat: allowing to activate sticky sessions on router

- src/git.rs
This CL aims to fix git broken tests making those parallelizable on the same test node.
> test: fixes git tests

- src/cmd/command.rs
- src/container_registry/docker.rs
- src/container_registry/docker_hub.rs
- src/container_registry/docr.rs
- src/container_registry/ecr.rs
- src/container_registry/mod.rs
- src/container_registry/scaleway_container_registry.rs
- src/errors/io.rs
- src/errors/mod.rs
- src/transaction.rs
- test_utilities/src/aws.rs
- test_utilities/src/digitalocean.rs
- test_utilities/src/scaleway.rs
> feat: migrate container registries to new logging

- src/dns_provider/mod.rs
> feat: migrate DNS providers to new logging

- src/build_platform/local_docker.rs
- src/cmd/command.rs
- src/cmd/docker.rs
- src/cmd/helm.rs
- src/cmd/kubectl.rs
To allow to customize how we want to cancel a command, instead of passing 1 argument for every method.
Will be needed for helm.
> Allow to customize how to abort a command

- src/cloud_provider/digitalocean/kubernetes/mod.rs
- src/cloud_provider/kubernetes.rs
- src/cloud_provider/scaleway/kubernetes/mod.rs
- src/errors/io.rs
- src/errors/mod.rs
- src/object_storage/errors.rs
- src/object_storage/mod.rs
- src/object_storage/s3.rs
- src/object_storage/scaleway_object_storage.rs
- src/object_storage/spaces.rs
- tests/scaleway/scw_container_registry.rs
> feat: object storage to use new logging

- src/cloud_provider/aws/databases/mongodb.rs
- src/cloud_provider/aws/databases/mysql.rs
- src/cloud_provider/aws/databases/postgresql.rs
- src/cloud_provider/aws/databases/redis.rs
- src/cloud_provider/aws/databases/utilities.rs
- src/cloud_provider/aws/kubernetes/mod.rs
- src/cloud_provider/digitalocean/kubernetes/doks_api.rs
- src/cloud_provider/digitalocean/kubernetes/mod.rs
- src/cloud_provider/helm.rs
- src/cloud_provider/kubernetes.rs
- src/cloud_provider/scaleway/kubernetes/mod.rs
- src/cloud_provider/service.rs
- src/cmd/helm.rs
- src/cmd/kubectl.rs
- src/cmd/terraform.rs
- src/errors/io.rs
- src/errors/mod.rs
- src/events/mod.rs
- src/io_models.rs
- test_utilities/src/utilities.rs
> fix: avoid leaking details to legacy errors

- src/cloud_provider/service.rs
- src/errors/mod.rs
- src/events/mod.rs
> fix: avoid leaking env vars to listeners

- src/build_platform/local_docker.rs
- src/build_platform/mod.rs
- src/cmd/docker.rs
> feat: adding extra docker build summary log

- src/cloud_provider/kubernetes.rs
- tests/digitalocean/do_databases.rs
- tests/digitalocean/do_kubernetes.rs
- tests/digitalocean/do_whole_enchilada.rs
To be fixed definitively once certmanager refacto will be over
> fix: functional tests issues

- src/cloud_provider/kubernetes.rs
Speed up environment delete and fix possible issues occuring because of required redeploy before destroy terraform side
> feat: speed up env delete

- lib/aws/charts/q-application/templates/deployment.j2.yaml
- lib/aws/charts/q-application/templates/horizontal_autoscaler.j2.yaml
- lib/aws/charts/q-application/templates/networkpolicies.j2.yaml
- lib/aws/charts/q-application/templates/pdb.j2.yaml
- lib/aws/charts/q-application/templates/secret.j2.yaml
- lib/aws/charts/q-application/templates/service.j2.yaml
- lib/aws/charts/q-application/templates/statefulset.j2.yaml
- lib/digitalocean/charts/q-application/templates/deployment.j2.yaml
- lib/digitalocean/charts/q-application/templates/horizontal_autoscaler.j2.yaml
- lib/digitalocean/charts/q-application/templates/pdb.j2.yaml
- lib/digitalocean/charts/q-application/templates/secret.j2.yaml
- lib/digitalocean/charts/q-application/templates/service.j2.yaml
- lib/digitalocean/charts/q-application/templates/statefulset.j2.yaml
- lib/scaleway/charts/q-application/templates/deployment.j2.yaml
- lib/scaleway/charts/q-application/templates/horizontal_autoscaler.j2.yaml
- lib/scaleway/charts/q-application/templates/networkpolicies.j2.yaml
- lib/scaleway/charts/q-application/templates/pdb.j2.yaml
- lib/scaleway/charts/q-application/templates/secret.j2.yaml
- lib/scaleway/charts/q-application/templates/service.j2.yaml
- lib/scaleway/charts/q-application/templates/statefulset.j2.yaml
- src/io_models.rs
- src/models/application.rs
- src/utilities.rs
- test_utilities/src/common.rs
- tests/aws/aws_environment.rs
- tests/digitalocean/do_environment.rs
- tests/scaleway/scw_environment.rs
Can't change stuff in selectors, as it is an immutable field for kubernetes
> Add long_id for applications

- .github/workflows/tests.yml
- tests: fix sccache release retrieval
> tests: fix sccache release retrieval

- lib/aws/bootstrap/chart_values/nginx-ingress.j2.yaml
- lib/digitalocean/bootstrap/chart_values/nginx-ingress.j2.yaml
- lib/scaleway/bootstrap/chart_values/nginx-ingress.j2.yaml
- src/cloud_provider/aws/kubernetes/mod.rs
- src/cloud_provider/digitalocean/kubernetes/mod.rs
- src/cloud_provider/scaleway/kubernetes/mod.rs
- test_utilities/src/aws.rs
- test_utilities/src/cloudflare.rs
- test_utilities/src/common.rs
- test_utilities/src/digitalocean.rs
- test_utilities/src/scaleway.rs
- tests/aws/aws_kubernetes.rs
- tests/scaleway/scw_kubernetes.rs
> fix: add wildcarded cluster domain to dns provider
